swagger: "2.0"
info:
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /resumes:
    get:
      tags:
      - resume
      summary: list resume
      description: List all stored resumes
      operationId: resume#list
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ResumeStoredResumeResponseCollection'
      schemes:
      - http
    post:
      tags:
      - resume
      summary: add resume
      description: Add n number of resumes and return their IDs. This is a multipart
        request and each part has field name 'resume' and contains the encoded resume
        to be added.
      operationId: resume#add
      parameters:
      - name: array
        in: body
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/ResumeRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: integer
              example: 1119650286328513290
              format: int64
      schemes:
      - http
definitions:
  EducationRequestBody:
    title: EducationRequestBody
    type: object
    properties:
      institution:
        type: string
        description: Name of the institution
        example: Est et nesciunt.
      major:
        type: string
        description: Major name
        example: Sed asperiores quos.
    example:
      institution: Provident in dolorum consequuntur.
      major: Maxime enim.
    required:
    - institution
    - major
  EducationResponse:
    title: EducationResponse
    type: object
    properties:
      institution:
        type: string
        description: Name of the institution
        example: Sapiente facilis et.
      major:
        type: string
        description: Major name
        example: Distinctio at amet velit et sequi atque.
    example:
      institution: Velit est.
      major: Occaecati omnis ratione perferendis quo consequatur.
    required:
    - institution
    - major
  ExperienceRequestBody:
    title: ExperienceRequestBody
    type: object
    properties:
      company:
        type: string
        description: Name of the company
        example: Pariatur at.
      duration:
        type: integer
        description: Duration (in years) in the company
        example: 7996747508154647781
        format: int64
      role:
        type: string
        description: Name of the role in the company
        example: Consequatur qui voluptatem aut adipisci.
    example:
      company: Dolorum id deleniti aut.
      duration: 295893699218251583
      role: Unde nesciunt similique vitae sit et quo.
    required:
    - company
    - role
    - duration
  ExperienceResponse:
    title: ExperienceResponse
    type: object
    properties:
      company:
        type: string
        description: Name of the company
        example: Totam omnis sunt molestiae magni totam numquam.
      duration:
        type: integer
        description: Duration (in years) in the company
        example: 2708610669982169212
        format: int64
      role:
        type: string
        description: Name of the role in the company
        example: Ut dolorem sit.
    example:
      company: Dignissimos qui rerum officiis ut.
      duration: 5756769045444272210
      role: Velit voluptas.
    required:
    - company
    - role
    - duration
  ResumeRequestBody:
    title: ResumeRequestBody
    type: object
    properties:
      education:
        type: array
        items:
          $ref: '#/definitions/EducationRequestBody'
        description: Education section in the resume
        example:
        - institution: Error accusantium autem asperiores reprehenderit dolorem.
          major: Id ipsam consectetur omnis earum eos.
        - institution: Error accusantium autem asperiores reprehenderit dolorem.
          major: Id ipsam consectetur omnis earum eos.
      experience:
        type: array
        items:
          $ref: '#/definitions/ExperienceRequestBody'
        description: Experience section in the resume
        example:
        - company: Qui repellat eveniet dignissimos et reiciendis.
          duration: 9027220452237938752
          role: Quia hic.
        - company: Qui repellat eveniet dignissimos et reiciendis.
          duration: 9027220452237938752
          role: Quia hic.
        - company: Qui repellat eveniet dignissimos et reiciendis.
          duration: 9027220452237938752
          role: Quia hic.
      name:
        type: string
        description: Name in the resume
        example: Ut ut quod.
    example:
      education:
      - institution: Error accusantium autem asperiores reprehenderit dolorem.
        major: Id ipsam consectetur omnis earum eos.
      - institution: Error accusantium autem asperiores reprehenderit dolorem.
        major: Id ipsam consectetur omnis earum eos.
      - institution: Error accusantium autem asperiores reprehenderit dolorem.
        major: Id ipsam consectetur omnis earum eos.
      - institution: Error accusantium autem asperiores reprehenderit dolorem.
        major: Id ipsam consectetur omnis earum eos.
      experience:
      - company: Qui repellat eveniet dignissimos et reiciendis.
        duration: 9027220452237938752
        role: Quia hic.
      - company: Qui repellat eveniet dignissimos et reiciendis.
        duration: 9027220452237938752
        role: Quia hic.
      name: Quia illum.
    required:
    - name
  ResumeStoredResumeResponseCollection:
    title: 'Mediatype identifier: application/vnd.goa.resume; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/StoredResumeResponse'
    description: ListResponseBody is the result type for an array of StoredResumeResponse
      (default view)
    example:
    - created_at: Vel aliquid maiores.
      education:
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      experience:
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      id: 6124869648451687649
      name: Aut suscipit et in voluptatem asperiores.
    - created_at: Vel aliquid maiores.
      education:
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      experience:
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      id: 6124869648451687649
      name: Aut suscipit et in voluptatem asperiores.
  StoredResumeResponse:
    title: 'Mediatype identifier: application/vnd.goa.resume; view=default'
    type: object
    properties:
      created_at:
        type: string
        description: Time when resume was created
        example: Quia neque occaecati saepe voluptatibus.
      education:
        type: array
        items:
          $ref: '#/definitions/EducationResponse'
        description: Education section in the resume
        example:
        - institution: Voluptas quos.
          major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
        - institution: Voluptas quos.
          major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      experience:
        type: array
        items:
          $ref: '#/definitions/ExperienceResponse'
        description: Experience section in the resume
        example:
        - company: Repudiandae hic explicabo et incidunt dolorem nulla.
          duration: 1592962344307484117
          role: Magnam consectetur quisquam minima mollitia.
        - company: Repudiandae hic explicabo et incidunt dolorem nulla.
          duration: 1592962344307484117
          role: Magnam consectetur quisquam minima mollitia.
        - company: Repudiandae hic explicabo et incidunt dolorem nulla.
          duration: 1592962344307484117
          role: Magnam consectetur quisquam minima mollitia.
        - company: Repudiandae hic explicabo et incidunt dolorem nulla.
          duration: 1592962344307484117
          role: Magnam consectetur quisquam minima mollitia.
      id:
        type: integer
        description: ID of the resume
        example: 1901607628517323986
        format: int64
      name:
        type: string
        description: Name in the resume
        example: Omnis nesciunt.
    description: StoredResumeResponse result type (default view)
    example:
      created_at: Aut atque numquam cum omnis illum.
      education:
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      - institution: Voluptas quos.
        major: Dolores necessitatibus vel tempora voluptatem voluptas earum.
      experience:
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      - company: Repudiandae hic explicabo et incidunt dolorem nulla.
        duration: 1592962344307484117
        role: Magnam consectetur quisquam minima mollitia.
      id: 8445392892696100585
      name: Et delectus est sed.
    required:
    - id
    - name
    - experience
    - education
    - created_at
